/**
 * Seed the resource-classes DynamoDB table with hierarchy data.
 *
 * Reads the static resource class tree from src/data/resource-class-tree.json
 * (generated by scripts/scrape-resource-tree.ts) and writes all entries to
 * the resource-classes DynamoDB table in LocalStack.
 *
 * This script is idempotent -- PutItem overwrites existing items, so it's
 * safe to re-run if the source data is updated.
 *
 * Prerequisites:
 *   1. LocalStack running (docker compose up -d)
 *   2. Table created (npm run tofu:apply:classification)
 *   3. Tree data scraped (npm run scrape:tree)
 *
 * Run with: npm run seed:classes
 */

import { readFileSync } from "node:fs";
import { BatchWriteCommand } from "@aws-sdk/lib-dynamodb";
import {
  createDocClient,
  RESOURCE_CLASSES_TABLE,
} from "../src/config.js";

// ─── Types ───────────────────────────────────────────────────────────

/** Shape of entries in resource-class-tree.json (from the scrape script) */
interface TreeEntry {
  nodeId: number;
  className: string;
  classId: string;
  parentNodeId: number;
  parentName: string | null;
  parentClassId: string | null;
  path: string;
  depth: number;
  isLeaf: boolean;
  statCaps: Record<string, [number, number]>;
}

// ─── Constants ───────────────────────────────────────────────────────

const TREE_PATH = "src/data/resource-class-tree.json";
const BATCH_SIZE = 25; // DynamoDB BatchWriteItem limit

// ─── Main ────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.log("=== Seed Resource Classes ===\n");

  // Read tree data
  console.log(`  Reading ${TREE_PATH}...`);
  const raw = readFileSync(TREE_PATH, "utf-8");
  const entries: TreeEntry[] = JSON.parse(raw);
  console.log(`  Loaded ${entries.length} class nodes`);

  const docClient = createDocClient();

  // Convert tree entries to DynamoDB items
  const items = entries.map((entry) => {
    // Convert statCaps from [min, max] tuples to { min, max } objects
    const statCaps: Record<string, { min: number; max: number }> = {};
    for (const [key, [min, max]] of Object.entries(entry.statCaps)) {
      statCaps[key] = { min, max };
    }

    return {
      classId: entry.classId,
      className: entry.className,
      pk: "CLASS", // Fixed partition key for by-path GSI
      parentClassId: entry.parentClassId ?? "ROOT", // DynamoDB GSI keys can't be null
      parentName: entry.parentName,
      treePath: entry.path,
      depth: entry.depth,
      isLeaf: entry.isLeaf,
      nodeId: entry.nodeId,
      statCaps,
    };
  });

  // Batch write in chunks of 25
  let written = 0;
  for (let i = 0; i < items.length; i += BATCH_SIZE) {
    const batch = items.slice(i, i + BATCH_SIZE);

    await docClient.send(
      new BatchWriteCommand({
        RequestItems: {
          [RESOURCE_CLASSES_TABLE]: batch.map((item) => ({
            PutRequest: { Item: item },
          })),
        },
      })
    );

    written += batch.length;
    // Progress every 100 items
    if (written % 100 < BATCH_SIZE) {
      console.log(`  Written ${written}/${items.length} items...`);
    }
  }

  console.log(`\n  Done! Seeded ${written} items into ${RESOURCE_CLASSES_TABLE}`);

  // Quick verification: count items with a scan
  const { ScanCommand } = await import("@aws-sdk/lib-dynamodb");
  let count = 0;
  let lastKey: Record<string, unknown> | undefined;
  do {
    const result = await docClient.send(
      new ScanCommand({
        TableName: RESOURCE_CLASSES_TABLE,
        Select: "COUNT",
        ExclusiveStartKey: lastKey,
      })
    );
    count += result.Count ?? 0;
    lastKey = result.LastEvaluatedKey as Record<string, unknown> | undefined;
  } while (lastKey);

  console.log(`  Verification: ${count} items in table\n`);

  if (count !== entries.length) {
    console.error(`  ERROR: Expected ${entries.length} items but found ${count}`);
    process.exit(1);
  }
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
